# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'Rotten Tomatoes' do

pod 'AFNetworking', '~> 2.4'
pod 'SVProgressHUD'
pod 'FontAwesome-iOS'
pod 'ODRefreshControl'

end

target 'Rotten TomatoesTests' do

end

